import React, { useRef, useState } from "react";
import {
    Box,
    Typography,
    Button,
    Card,
    Divider,
    Skeleton,
    Tooltip,
} from "@mui/material";

import {
    CopyIcon,
    ShareIcon,
} from "@/components/icons";

import {
    copyReferralLink,
    shareOnX,
} from "@/utils/referral";

interface Props {
    loading?: boolean;
    disabled?: boolean;
    data: {
        link: string;
        shareLink: string;
        invitedUsers: number;
        approvedPosts: number;
        earnedQP: number;
    };
}

export const ReferralCard = ({
    data,
    loading = false,
    disabled = false,
}: Props) => {
    const isNotLink = data?.link === "";
    const [copiedOpen, setCopiedOpen] = useState(false);
    const copiedTimeoutRef = useRef<ReturnType<typeof setTimeout>>();

    const handleCopyLink = async () => {
        await copyReferralLink(data.link);
        setCopiedOpen(true);

        if (copiedTimeoutRef.current) {
            clearTimeout(copiedTimeoutRef.current);
        }

        copiedTimeoutRef.current = setTimeout(() => {
            setCopiedOpen(false);
        }, 1500);
    };

    return (
        <Card
            sx={{
                p: { xs: 2.5, md: 4 },
                borderRadius: "16px",
                border: "1px solid #003EC733",
                boxShadow: "none",
                mb: 4,
            }}
        >
            <Box
                sx={{
                    display: "flex",
                    flexDirection: {
                        xs: "column",
                        lg: "row",
                    },
                    gap: 4,
                    alignItems: {
                        lg: "center",
                    },
                }}
            >
                <Box sx={{ flex: 0.7 }}>
                    <Typography
                        sx={{
                            color: "#003EC7",
                            fontSize: "12px",
                            fontWeight: 600,
                            mb: 1,
                        }}
                    >
                        50% Referral Reward
                    </Typography>

                    <Typography
                        sx={{
                            fontWeight: 700,
                            fontSize: "18px",
                            color: "#111827",
                            mb: 1,
                        }}
                    >
                        Invite Contributors. Earn More
                        QP.
                    </Typography>

                    <Typography
                        sx={{
                            color: "#5E5E61",
                            fontSize: "16px",
                            lineHeight: 1.5,
                        }}
                    >
                        Invite friends to join
                        Qantera. Earn 50% of the QP
                        generated by every approved Yap
                        post they submit.
                    </Typography>
                </Box>

                <Box
                    sx={{
                        flex: 1.5,
                        display: "flex",
                        flexDirection: {
                            xs: "column",
                            sm: "row",
                        },
                        gap: 3,
                        alignItems: "center",
                    }}
                >
                    <Box
                        sx={{
                            width: "100%",
                            flex: 1.3,
                        }}
                    >
                        <Box
                            sx={{
                                bgcolor: "#F7F7F7",
                                p: 2,
                                borderRadius: "100px",
                                textAlign: "center",
                                mb: 1.5,
                                border:
                                    "1px solid #DEE1E6",
                                display: "flex",
                                justifyContent:
                                    "center",
                                alignItems: "center",
                            }}
                        >
                            {loading ? (
                                <Skeleton
                                    width="100%"
                                    height={18}
                                />
                            ) : (
                                <Typography
                                    sx={{
                                        fontSize:
                                            "12px",
                                        color:
                                            "#4B5563",
                                        fontFamily:
                                            "var(--font-jetBrain-mono)",
                                        whiteSpace:
                                            "nowrap",
                                        overflow:
                                            "hidden",
                                        textOverflow:
                                            "ellipsis",
                                        width:
                                            "100%",
                                        px: 1,
                                    }}
                                >
                                    {data.link}
                                </Typography>
                            )}
                        </Box>

                        <Box
                            sx={{
                                display: "flex",
                                gap: 1.5,
                            }}
                        >
                            <Tooltip
                                title="Copied!"
                                open={copiedOpen}
                                arrow
                                placement="top"
                                disableFocusListener
                                disableHoverListener
                                disableTouchListener
                                onClose={() => setCopiedOpen(false)}
                            >
                                <Box
                                    component="span"
                                    sx={{
                                        flex: 1,
                                        display: "flex",
                                    }}
                                >
                                    <Button
                                        variant="contained"
                                        disabled={
                                            disabled ||
                                            loading || isNotLink
                                        }
                                        startIcon={
                                            <CopyIcon />
                                        }
                                        onClick={handleCopyLink}
                                        sx={{
                                            flex: 1,
                                            bgcolor:
                                                "#003EC7",
                                            borderRadius:
                                                "100px",
                                            textTransform:
                                                "none",
                                            fontSize:
                                                "13px",
                                            fontWeight: 600,
                                            py: 1,
                                        }}
                                    >
                                        Copy Link
                                    </Button>
                                </Box>
                            </Tooltip>

                            <Button
                                variant="outlined"
                                disabled={
                                    disabled ||
                                    loading || isNotLink
                                }
                                startIcon={
                                    <ShareIcon />
                                }
                                onClick={() =>
                                    shareOnX(
                                        data.shareLink
                                    )
                                }
                                sx={{
                                    flex: 1,
                                    color:
                                        "#111827",
                                    borderColor:
                                        "#E5E7EB",
                                    borderRadius:
                                        "100px",
                                    textTransform:
                                        "none",
                                    fontSize:
                                        "13px",
                                    fontWeight: 600,
                                }}
                            >
                                Share on X
                            </Button>
                        </Box>
                    </Box>

                    <Divider
                        orientation="vertical"
                        flexItem
                        sx={{
                            display: {
                                xs: "none",
                                sm: "block",
                            },
                        }}
                    />

                    <Box
                        sx={{
                            width: {
                                xs: "100%",
                                sm: "180px",
                            },
                            display: "flex",
                            flexDirection: "column",
                            gap: 1.5,
                            flex: 0.7,
                        }}
                    >
                        {loading ? (
                            <>
                                <Skeleton
                                    height={28}
                                />
                                <Skeleton
                                    height={28}
                                />
                                <Skeleton
                                    height={28}
                                />
                            </>
                        ) : (
                            <>
                                <Box
                                    sx={{
                                        display:
                                            "flex",
                                        justifyContent:
                                            "space-between",
                                    }}
                                >
                                    <Typography
                                        sx={{
                                            fontWeight:
                                                500,
                                            color:
                                                "#6B7280",
                                        }}
                                    >
                                        Invited Users:
                                    </Typography>

                                    <Typography
                                        sx={{
                                            fontSize:
                                                "16px",
                                            fontWeight: 700,
                                        }}
                                    >
                                        {
                                            data.invitedUsers
                                        }
                                    </Typography>
                                </Box>

                                <Box
                                    sx={{
                                        display:
                                            "flex",
                                        justifyContent:
                                            "space-between",
                                    }}
                                >
                                    <Typography
                                        sx={{
                                            fontWeight:
                                                500,
                                            color:
                                                "#6B7280",
                                        }}
                                    >
                                        Approved
                                        Posts:
                                    </Typography>

                                    <Typography
                                        sx={{
                                            fontSize:
                                                "16px",
                                            fontWeight: 700,
                                        }}
                                    >
                                        {
                                            data.approvedPosts
                                        }
                                    </Typography>
                                </Box>

                                <Box
                                    sx={{
                                        display:
                                            "flex",
                                        justifyContent:
                                            "space-between",
                                    }}
                                >
                                    <Typography
                                        sx={{
                                            fontWeight:
                                                500,
                                            color:
                                                "#6B7280",
                                        }}
                                    >
                                        Referral QP:
                                    </Typography>

                                    <Typography
                                        sx={{
                                            fontSize:
                                                "18px",
                                            fontWeight: 700,
                                            color:
                                                "#003EC7",
                                            fontFamily:
                                                "var(--font-jetBrain-mono)",
                                        }}
                                    >
                                        {
                                            data.earnedQP
                                        }{" "}
                                        QP
                                    </Typography>
                                </Box>
                            </>
                        )}
                    </Box>
                </Box>
            </Box>
        </Card>
    );
};